Repository fetchai/agents-tac, pull requests merged in 2019-07, with the labels that each got.

#248 refactor simulation script and agent scripts.
  docker-tac-develop/Dockerfile
  simulation/v1/tac_agent_spawner.py
  tac/agents/v1/base/participant_agent.py
  tac/agents/v1/examples/baseline.py
  tac/platform/controller.py
  templates/README.md
  templates/v1/advanced.py
  templates/v1/basic.py
  templates/v1/expert.py
Labels: enhancement

#261 Fx misc issues in gui modules.
  Pipfile
  Pipfile.lock
  tac/gui/dashboards/agent.py
  tac/gui/dashboards/base.py
  tac/gui/dashboards/controller.py
Labels: bug

#262 Make the agent loop until a controller is found
  tac/agents/v1/base/participant_agent.py
  tac/agents/v1/base/reactions.py
Labels: enhancement

#265 Add code style check to the CI Pipeline.
  Jenkinsfile
Labels: test

#268 Fix terminate method of ControllerAgent.
  tac/platform/controller.py
Labels: bug

#277 Adds callbacks for error handling to controller agent.
  tac/agents/v1/base/reactions.py
  tac/platform/controller.py
Labels: enhancement
